server:
  port: 6001
spring:
  application:
    name: cloud-bank2-provider
  cloud:
    nacos:
      discovery:
        server-addr: centos.orb.local:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://centos.orb.local:3306/bank_2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: myOcP!eBZ56ahvtz

seata:
  registry:
    type: file
  service:
    grouplist:
      default: centos.orb.local:8090
    vgroup-mapping:
      my_test_tx_group: default
  tx-service-group: my_test_tx_group
